bibliotecasRename =     {'Cod_Loc':'cod_localidad',
                        'IdProvincia':'id_provincia',
                        'IdDepartamento':'id_departamento',
                        'Categoría':'categoria',
                        'Provincia':'provincia',
                        'Localidad':'localidad',
                        'Nombre':'nombre',
                        'Domicilio':'domicilio',
                        'CP':'codigo_postal',
                        'Teléfono':'numero_de_telefono',
                        'Mail':'mail','Web':'web'}

cinesRename =   {'Cod_Loc':'cod_localidad',
                'IdProvincia':'id_provincia',
                'IdDepartamento':'id_departamento',
                'Categoría':'categoria',
                'Provincia':'provincia',
                'Localidad':'localidad',
                'Nombre':'nombre',
                'Dirección':'domicilio',
                'CP':'código_postal',
                'Teléfono':'numero_de_telefono',
                'Mail':'mail',
                'Web':'web'}

museosRename =  {'Cod_Loc':'cod_localidad',
                'IdProvincia':'id_provincia',
                'IdDepartamento':'id_departamento',
                'categoria':'categoria',
                'Provincia':'provincia',
                'Localidad':'localidad',
                'Nombre':'nombre',
                'direccion':'domicilio',
                'CP':'codigo_postal',
                'telefono':'numero_de_telefono',
                'Mail':'mail',
                'Web':'web'}
        